version: 0.2

env:
  variables:
    REPO_NAME: blog-app-03
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - jq --version || yum install jq -y
      - export ACCOUNT_ID=`aws sts get-caller-identity | jq -r .Account`
      - echo ACCOUNT ID $ACCOUNT_ID - Region $AWS_REGION
      - export DKR_ACCT_URL="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - echo $DKR_ACCT_URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DKR_ACCT_URL
      - if [ -z ${CODEBUILD_BUILD_NUMBER+x} ]; then export BUILD_NUMBER=$(date +%s); else export BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER; fi
      - export TAG=${REPO_NAME}:${BUILD_NUMBER}
      - echo Tag ${TAG} - Account ID $ACCOUNT_ID
  pre_build:
    commands:
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install --upgrade -r requirements.txt
      - pip install --upgrade -r requirements_dev.txt
  build:
    commands:
      - docker build -t ${TAG} . && export TAG_URL="${DKR_ACCT_URL}/${REPO_NAME}:${BUILD_NUMBER}"
      - docker build -t ${TAG_URL} .
      - docker push ${TAG_URL} && echo ${TAG_URL} > image_id.txt

artifacts:
  name: ImageId
  files:
    - image_id.txt
